package kernel;

const (
	COLOR_BLACK = iota
	COLOR_BLUE
	COLOR_GREEN
	COLOR_CYAN 
	COLOR_RED 
	COLOR_MAGENTA 
	COLOR_BROWN 
	COLOR_LIGHT_GREY 
	COLOR_DARK_GREY 
	COLOR_LIGHT_BLUE 
	COLOR_LIGHT_GREEN 
	COLOR_LIGHT_CYAN
	COLOR_LIGHT_RED
	COLOR_LIGHT_MAGENTA 
	COLOR_LIGHT_BROWN 
	COLOR_WHITE 
)

func Testo(c *uint8) {
	*c = 'G'
//	_c = 'T'
	//print("This is from Go")
}